@startuml



class "Vaccine Recipient"{
    name
    phone_number
    id

}


class doctor{
    clinic
    accreditation
}

class vaccine {
    date
}



"Vaccine Recipient" "1" -- "1" vaccine : receives >
doctor "1" -- "1" vaccine : gives >


@enduml



